{"name": "Ошибка при попытке принять заказ без или с неверным id курьера", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id курьера.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "808012"}], "start": 1733420325352, "stop": 1733420325442}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "386382"}, {"name": "courier_id", "value": "0"}], "start": 1733420325442, "stop": 1733420325489}], "parameters": [{"name": "courier_id", "value": "0"}, {"name": "expected", "value": "(404, 'Курьера с таким id не существует')"}], "start": 1733420325351, "stop": 1733420325489, "uuid": "b525e6c2-6bcb-4806-9930-f71672cd0118", "historyId": "069cc3491c7469a8532b5a49dab8db58", "testCaseId": "abe11c86ff0e6a83e2122a43b64dc9d7", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "14132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}