{"name": "Ошибка при попытке получить данные заказа без или по неверному трек-номеру", "status": "passed", "description": "Ошибка при попытке получить данные заказа без или по неверному\n        трек-номеру.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "0"}], "start": 1733420254603, "stop": 1733420256607}], "parameters": [{"name": "track", "value": "0"}, {"name": "expected", "value": "(404, 'Заказ не найден')"}], "start": 1733420254603, "stop": 1733420256607, "uuid": "d6cda8f7-7743-4138-a18e-245b13783ace", "historyId": "e400a2fce6f9f785a0aab6bc7e3e6e40", "testCaseId": "9e3242c7a012519dd2d3dee5a0b56136", "fullName": "tests.orders.test_orders_get.TestOrdersGet#test_get_order_no_or_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_get"}, {"name": "subSuite", "value": "TestOrdersGet"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_get"}]}