{"name": "Ошибка при попытке принять заказ без или с неверным id курьера", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id курьера.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "82292"}], "start": 1733420192589, "stop": 1733420192691}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "386373"}, {"name": "courier_id", "value": "0"}], "start": 1733420192691, "stop": 1733420192759}], "parameters": [{"name": "courier_id", "value": "0"}, {"name": "expected", "value": "(404, 'Курьера с таким id не существует')"}], "start": 1733420192589, "stop": 1733420192760, "uuid": "109f6224-2aae-4911-9335-49fe3cdd4e13", "historyId": "069cc3491c7469a8532b5a49dab8db58", "testCaseId": "abe11c86ff0e6a83e2122a43b64dc9d7", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}