{"name": "Ошибка при попытке получить данные заказа без или по неверному трек-номеру", "status": "passed", "description": "Ошибка при попытке получить данные заказа без или по неверному\n        трек-номеру.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "None"}], "start": 1733420254541, "stop": 1733420254589}], "parameters": [{"name": "track", "value": "None"}, {"name": "expected", "value": "(400, 'Недостаточно данных для поиска')"}], "start": 1733420254541, "stop": 1733420254589, "uuid": "d6793635-3acc-4783-b8d3-ab01066bda24", "historyId": "0f88cec768cdee82c35103c6caa4de7b", "testCaseId": "9e3242c7a012519dd2d3dee5a0b56136", "fullName": "tests.orders.test_orders_get.TestOrdersGet#test_get_order_no_or_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_get"}, {"name": "subSuite", "value": "TestOrdersGet"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_get"}]}